name: my_pendrive_wallet_desktop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pie_chart: ^5.1.0
  localized: ^2.1.1
  shared_preferences: ^2.0.13
  encrypted_shared_preferences: ^3.0.0
  qr_flutter: ^4.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/logo.png
    - assets/menu.png
    - assets/arrow_back.png
    - assets/add.png
    - assets/alert.png
    - assets/chart.png
    - assets/export.png
    - assets/help.png
    - assets/home.png
    - assets/import.png
    - assets/lock.png
    - assets/logout.png
    - assets/scan.png
    - assets/transfer.png
    - assets/user.png
    - assets/wallet.png
    - assets/trash.png
    - assets/cryptoIcons/32x32/Bitcoin.png
    - assets/cryptoIcons/32x32/Ethereum.png
    - assets/cryptoIcons/64x64/Bitcoin.png
    - assets/cryptoIcons/64x64/Ethereum.png
    - assets/cryptoIcons/128x128/Bitcoin.png
    - assets/cryptoIcons/128x128/Ethereum.png
    - assets/cryptoIcons/256x256/Bitcoin.png
    - assets/cryptoIcons/256x256/Ethereum.png
  # fonts:
  #   - family: MyCustomIcons
  #     fonts:
  #       - asset: assets/customIcons/fonts/MyCustomIcons.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
